spring:
  application:
    name: zuul-server
server:
  port: 9093

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9091/eureka/

zuul:
  routes:
    eureka-client-url:
      path: /eureka-client-url/**
      url: http://localhost:9092
    eureka-client-id:
      path: /eureka-client-id/**
      service-id: eureka-client


